### PR TITLE
Collect Nginx logs with Promtail and Loki

### PR DESCRIPTION
**Pull request by pinpox**

### CODE REVIEW

**Comment by pinpox** [comment]
Not working yet:
```
Jan 31 11:15:26 porree promtail[53196]: level=error ts=2022-01-31T10:15:26.10829847Z caller=client.go:360 component=client host=localhost:3100 msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): entry with timestamp 2022-01-31 09:37:44.230285 +0000 UTC ignored, reason: 'entry too far behind' for stream: {host=\"porree\", job=\"systemd-journal\"},"
```

**Comment by forgondolin** [comment]
Hello there, did you have any luck on this? I'm having a similar problem and even playing with Loki configs (reject old chunks and stuff) I couldn't make it work :/

**Comment by pinpox** [comment]
Hey! I havent finished this yet, but this branch was my last attempt. Not sure when I will have time for it currently :(

**Comment by pinpox** [comment]
No longer needed as I switched to caddy.

**Pull request closed without merging**
